#!/usr/bin/env php
<?php
declare(strict_types=1);

/**
 * Canned host agent for the README screenshots: same one-request-one-response
 * JSON-over-stdio shape as tests/fixtures/canned_agent.php, but with
 * presentable demo content instead of test cases. Read-only; nothing here
 * touches tmux, real sessions or real transcripts.
 *
 * Serve it (from the repo root):
 *   php tests/lib/socket_harness.php /tmp/sessioneer-demo.sock php docs/screenshots/demo_agent.php &
 *   SESSIONEER_AGENT_SOCKET=/tmp/sessioneer-demo.sock php -S 127.0.0.1:18750 -t public public/index.php
 * (18750 is clear of the ports the test suite binds), then capture
 * dashboard.png at 1440x1350, blocked-prompt.png
 * (/session.php?session=cc-20261006-0912) at 1440x840, and both mobile-*.png
 * at 390x844. The browser may reuse a cached page, so add a throwaway query string when
 * re-capturing after a code change.
 */

const DEMO_BLOCKED_SESSION = 'cc-20261006-0912';

$now = time();

$blockedPrompt = [
    'blocked_reason' => 'Do you want to proceed?',
    'prompt_context' => "Remove disposable build output directories\n\nrm -rf dist/ build/ .cache/",
    'prompt_options' => [['number' => 1, 'label' => 'Yes'], ['number' => 2, 'label' => 'No']],
    'prompt_is_folder_trust' => false,
];

$answer = "`rm -rf` on a known build-output directory (`dist/`, `build/`, `.cache/`) is fine when the path is "
    . "unambiguous and entirely disposable: it's fast and there's nothing to get wrong.\n\n"
    . "`find` is the right tool when you're matching artifacts *by pattern* across a tree "
    . "(`find . -name \"*.o\" -delete`, or files older than N days), because you can dry-run it with "
    . "`find ... -print` first. `rm -rf` has no preview step.\n\n"
    . "These three directories are all generated by the build, so I'll remove them directly.";

$sessions = [
    array_merge([
        'name' => DEMO_BLOCKED_SESSION,
        'activity' => $now - 240,
        'attached' => false,
        'workdir' => '/home/user/www/build-tools',
        'spawned_by_app' => true,
        'title' => 'Build artifact cleanup',
        'agent' => 'claude',
        'agent_label' => 'Claude Code',
        'status' => 'blocked',
        'working' => true,
        'context_used_percentage' => 18,
        'last_message' => ['role' => 'assistant', 'timestamp' => gmdate('c', $now - 240), 'blocks' => [['kind' => 'text', 'text' => $answer]]],
    ], $blockedPrompt),
    [
        'name' => 'codex-headless-20261006-0841',
        'activity' => $now - 20,
        'workdir' => '/home/user/www/payments-api',
        'spawned_by_app' => true,
        'title' => 'Add retry with backoff to the webhook client',
        'agent' => 'codex',
        'agent_label' => 'Codex',
        'runtime' => 'headless',
        'status' => 'working',
        'working' => true,
        'context_used_percentage' => 41,
        'last_message' => ['role' => 'assistant', 'timestamp' => gmdate('c', $now - 20), 'blocks' => [['kind' => 'text', 'text' => 'Retries now back off exponentially with jitter; running the client tests next.']]],
    ],
    [
        'name' => 'oc-20261006-0805',
        'activity' => $now - 1500,
        'workdir' => '/home/user/www/storefront',
        'spawned_by_app' => true,
        'title' => 'CI setup for the Node.js project',
        'agent' => 'opencode',
        'agent_label' => 'OpenCode',
        'runtime' => 'headless',
        'status' => 'idle',
        'working' => false,
        'last_message' => ['role' => 'assistant', 'timestamp' => gmdate('c', $now - 1500), 'blocks' => [['kind' => 'text', 'text' => 'The workflow now caches npm, runs lint and tests on Node 22 and 24, and uploads coverage.']]],
    ],
    [
        'name' => 'claude-headless-20261005-1630',
        'activity' => $now - 5400,
        'workdir' => '/home/user/www/docs-site',
        'spawned_by_app' => true,
        'title' => 'Draft the 2.4 release notes',
        'agent' => 'claude',
        'agent_label' => 'Claude Code',
        'runtime' => 'headless',
        'profile' => 'work',
        'status' => 'idle',
        'working' => false,
        'last_message' => ['role' => 'assistant', 'timestamp' => gmdate('c', $now - 5400), 'blocks' => [['kind' => 'text', 'text' => 'Draft saved to CHANGELOG.md, grouped into Features, Fixes and Upgrade notes.']]],
    ],
];

$history = [
    ['type' => 'user', 'role' => 'user', 'timestamp' => gmdate('c', $now - 330), 'line' => 1, 'blocks' => [['kind' => 'text', 'text' => 'What are the tradeoffs between rm -rf and a more selective find/delete when cleaning up old build artifacts in a project?']]],
    ['type' => 'assistant', 'role' => 'assistant', 'timestamp' => gmdate('c', $now - 300), 'line' => 2, 'blocks' => [['kind' => 'tool_use', 'text' => 'tool: Bash - command: du -sh dist build .cache', 'description' => 'Check the size of the build output directories', 'tool_name' => 'Bash', 'command' => 'du -sh dist build .cache']]],
    ['type' => 'user', 'role' => 'user', 'timestamp' => gmdate('c', $now - 295), 'line' => 3, 'blocks' => [['kind' => 'tool_result', 'text' => "412M\tdist\n96M\tbuild\n1.3G\t.cache"]]],
    ['type' => 'assistant', 'role' => 'assistant', 'timestamp' => gmdate('c', $now - 240), 'line' => 4, 'blocks' => [['kind' => 'text', 'text' => $answer]]],
];

$quota = [
    'session' => ['pct' => 38, 'resets_at' => $now + 2 * 3600],
    'week_all' => ['pct' => 21, 'resets_at' => $now + 3 * 86400],
    'captured_at' => gmdate('c', $now - 60),
];

$request = json_decode((string)stream_get_contents(STDIN), true);
$request = is_array($request) ? $request : [];
$isBlocked = ($request['session'] ?? null) === DEMO_BLOCKED_SESSION;

$response = match ($request['action'] ?? null) {
    'list' => ['ok' => true, 'sessions' => $sessions, 'bare' => []],
    'list_archived' => ['ok' => true, 'archived' => []],
    'session_detail' => $isBlocked
        ? array_merge($sessions[0], $blockedPrompt, [
            'ok' => true,
            'git_branch' => 'main',
            'current_mode' => 'manual',
            'current_model' => 'sonnet',
            'agent_session_id' => '3f6c2a9e-8d41-4b7a-9c15-2e7d0b4a6f13',
            'has_transcript' => true,
        ])
        : ['ok' => false, 'message' => 'Session not found'],
    'session_history' => $isBlocked
        ? ['ok' => true, 'entries' => $history, 'has_more' => false]
        : ['ok' => false, 'message' => 'No transcript recorded for this session'],
    'list_plan_files', 'list_uploaded_files' => ['ok' => true, 'files' => [], 'total_size' => 0],
    'health_check' => ['ok' => true, 'checks' => [['key' => 'agent', 'label' => 'Host agent', 'ok' => true, 'section' => 'Global']]],
    'check_session_hook' => ['ok' => true, 'installed' => true],
    'push_public_key' => ['ok' => true, 'configured' => false],
    'quota' => ['ok' => true, 'quota' => $quota, 'agents' => ['claude' => ['label' => 'Claude Code', 'ok' => true, 'quota' => $quota, 'fetched_at' => $now - 60, 'message' => null]], 'fetched_at' => $now - 60, 'cached' => true, 'stale' => false, 'refreshing' => false],
    'search_transcripts' => ['ok' => true, 'results' => []],
    default => ['ok' => false, 'message' => 'Not available in the screenshot demo'],
};

fwrite(STDOUT, json_encode($response));
